import {
  mobile,
  backend,
  creator,
  web,
  javascript,
  typescript,
  html,
  css,
  reactjs,
  nextjs,
  redux,
  tailwind,
  nodejs,
  mongodb,
  git,
  figma,
  docker,
  logoTag,
  logoEmutua,
  logoVivo,
  logoSesc,
  onefortwo,
  uber,
  renders,
  freelarest,
  instagram,
  tinder,
  threejs,
  android,
  apple,
  chromeIcon,
  github,
  atmaMeditation,
  avell,
  onthewall,
  scarflab,
  agcalifornia,
  empreenda
} from "../assets";

export const navLinks = [
  { id: "about", titleKey: "nav.about" },
  { id: "work", titleKey: "nav.work" },
  { id: "contact", titleKey: "nav.contact" },
];

const services = [
  { titleKey: "services.techLead", icon: creator, description: "" },
  { titleKey: "services.webDeveloper", icon: web, description: "" },
  { titleKey: "services.reactNativeDeveloper", icon: mobile, description: "" },
  { titleKey: "services.backendDeveloper", icon: backend, description: "" },
];

const technologies = [
  { name: "HTML 5", icon: html },
  { name: "CSS 3", icon: css },
  { name: "JavaScript", icon: javascript },
  { name: "TypeScript", icon: typescript },
  { name: "React JS", icon: reactjs },
  { name: "Next JS", icon: nextjs },
  { name: "Redux Toolkit", icon: redux },
  { name: "Tailwind CSS", icon: tailwind },
  { name: "Node JS", icon: nodejs },
  { name: "MongoDB", icon: mongodb },
  { name: "Three JS", icon: threejs },
  { name: "git", icon: git },
  { name: "figma", icon: figma },
  { name: "docker", icon: docker },
];

const experiences = [
  {
    titleKey: "experiences.vivo.title",
    company_name: "Vivo - Telefonica",
    icon: logoVivo,
    iconBg: "#ffffff",
    dateKey: "experiences.vivo.date",
    activities: [
      "experiences.vivo.activities.0",
      "experiences.vivo.activities.1",
      "experiences.vivo.activities.2",
      "experiences.vivo.activities.3",
    ],
  },
  {
    titleKey: "experiences.emutua.title",
    company_name: "eMutua Digital",
    icon: logoEmutua,
    iconBg: "#383E56",
    dateKey: "experiences.emutua.date",
    activities: [
      "experiences.emutua.activities.0",
      "experiences.emutua.activities.1",
      "experiences.emutua.activities.2",
      "experiences.emutua.activities.3",
    ],
  },
  {
    titleKey: "experiences.tag.title",
    company_name: "Tag Desenvolvimento",
    icon: logoTag,
    iconBg: "#383E56",
    dateKey: "experiences.tag.date",
    activities: [
      "experiences.tag.activities.0",
      "experiences.tag.activities.1",
      "experiences.tag.activities.2",
      "experiences.tag.activities.3",
      "experiences.tag.activities.4",
    ],
  },
  {
    titleKey: "experiences.sesc.title",
    company_name: "SESC SP",
    icon: logoSesc,
    iconBg: "#ffffff",
    dateKey: "experiences.sesc.date",
    activities: [
      "experiences.sesc.activities.0",
      "experiences.sesc.activities.1",
      "experiences.sesc.activities.2",
      "experiences.sesc.activities.3",
    ],
  },
];

const testimonials = [
  {
    testimonialKey: "testimonials.saraLee.testimonial",
    nameKey: "testimonials.saraLee.name",
    designationKey: "testimonials.saraLee.designation",
    companyKey: "testimonials.saraLee.company",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    testimonialKey: "testimonials.chrisBrown.testimonial",
    nameKey: "testimonials.chrisBrown.name",
    designationKey: "testimonials.chrisBrown.designation",
    companyKey: "testimonials.chrisBrown.company",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    testimonialKey: "testimonials.lisaWang.testimonial",
    nameKey: "testimonials.lisaWang.name",
    designationKey: "testimonials.lisaWang.designation",
    companyKey: "testimonials.lisaWang.company",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
];

const projects = [
  {
    id: "bc179a01-700f-4ca4-b020-3d8ba5bc3dd4",
    nameKey: "projects.atmaMeditacao.name",
    type: "collaborate",
    descriptionKey: "projects.atmaMeditacao.description",
    tags: [
      { name: "React Native", color: "blue-text-gradient" },
      { name: "React JS", color: "green-text-gradient" },
      { name: "Node-JS", color: "pink-text-gradient" },
      { name: "Java", color: "orange-text-gradient" },
    ],
    image: atmaMeditation,
    links: [
      { url: "https://www.atmameditacao.com.br", icon: chromeIcon, color: "bg-white", altKey: "common.accessWebsite" },
      { url: "https://play.google.com/store/apps/details?id=com.movile.meditation.vivo&hl=pt_BR&gl=US", icon: android, color: "bg-white", altKey: "common.accessGooglePlay" },
      { url: "https://apps.apple.com/br/app/atma-medita%C3%A7%C3%A3o-e-bem-estar/id1229827447", icon: apple, color: "bg-white", altKey: "common.accessAppleStore" },
    ],
  },
  {
    id: "883e01e0-8dcf-42c4-9e20-73d31de689f8",
    nameKey: "projects.avell.name",
    type: "collaborate",
    descriptionKey: "projects.avell.description",
    tags: [{ name: "React JS", color: "green-text-gradient" }],
    image: avell,
    links: [{ url: "https://avell.com.br", icon: chromeIcon, color: "bg-white", altKey: "common.accessWebsite" }],
  },
  {
    id: "0968a04c-d84f-4966-8eb6-9debb015e362",
    nameKey: "projects.oneForTwo.name",
    type: "personal",
    descriptionKey: "projects.oneForTwo.description",
    tags: [
      { name: "React Native", color: "blue-text-gradient" },
      { name: "Laravel", color: "green-text-gradient" },
      { name: "Next JS", color: "pink-text-gradient" },
    ],
    image: onefortwo,
    links: [
      { url: "https://www.personaisonefortwo.com.br", icon: chromeIcon, color: "bg-white", altKey: "common.accessWebsite" },
      { url: "https://play.google.com/store/apps/details?id=com.onefortwo", icon: android, color: "bg-white", altKey: "common.accessGooglePlay" },
      { url: "https://apps.apple.com/br/app/one-for-two/id6448317590?l=en", icon: apple, color: "bg-white", altKey: "common.accessAppleStore" },
      { url: "-", icon: github, color: "bg-gray-800", altKey: "common.accessWebsite", disabledColor: "dark", disabled: true },
    ],
  },
  {
    id: "397f566c-1ced-4555-b7c4-4ba8353d47fe",
    nameKey: "projects.onTheWall.name",
    type: "collaborate",
    descriptionKey: "projects.onTheWall.description",
    tags: [
      { name: "React Native", color: "blue-text-gradient" },
      { name: "Laravel", color: "green-text-gradient" },
      { name: "Next JS", color: "pink-text-gradient" },
    ],
    image: onthewall,
    links: [
      { url: "https://www.onthewall.com.br", icon: chromeIcon, color: "bg-white", altKey: "common.accessWebsite" },
      { url: "-", icon: github, color: "bg-gray-800", altKey: "common.accessWebsite", disabledColor: "dark", disabled: true },
    ],
  },
  {
    id: "6c2fd046-7676-46bf-b7cf-bffb50383388",
    nameKey: "projects.rendersAcademy.name",
    type: "personal",
    descriptionKey: "projects.rendersAcademy.description",
    tags: [
      { name: "Laravel", color: "pink-text-gradient" },
      { name: "PHP", color: "blue-text-gradient" },
      { name: "MySql", color: "green-text-gradient" },
      { name: "Template Blade", color: "text-orange-500" },
    ],
    image: renders,
    links: [
      { url: "https://www.rendersacademy.com.br", icon: chromeIcon, color: "bg-white", altKey: "common.accessWebsite" },
      { url: "-", icon: github, color: "bg-gray-800", altKey: "common.accessWebsite", disabledColor: "dark", disabled: true },
    ],
  },
  {
    id: "964ded32-8053-492d-a9c3-240a8e6870bb",
    nameKey: "projects.freelarest.name",
    type: "personal",
    descriptionKey: "projects.freelarest.description",
    tags: [
      { name: "Laravel", color: "pink-text-gradient" },
      { name: "PHP", color: "blue-text-gradient" },
      { name: "Next JS", color: "green-text-gradient" },
    ],
    image: freelarest,
    links: [
      { url: "https://www.freelarest.com", icon: chromeIcon, color: "bg-white", altKey: "common.accessWebsite" },
      { url: "", icon: github, color: "bg-gray-800", altKey: "common.accessWebsite", disabledColor: "dark", disabled: true },
    ],
  },
  {
    id: "6b7f9303-621b-433c-b5a3-5883e031c093",
    nameKey: "projects.scarfLab.name",
    type: "collaborate",
    tags: [
      { name: "Laravel", color: "pink-text-gradient" },
      { name: "PHP", color: "blue-text-gradient" },
    ],
    image: scarflab,
    links: [{ url: "", icon: github, color: "bg-gray-800", altKey: "common.accessWebsite", disabledColor: "dark", disabled: true }],
  },
  {
    id: "ae103edb-40cf-42dd-b302-c696d72fa37e",
    nameKey: "projects.agenciaCalifornia.name",
    type: "collaborate",
    tags: [
      { name: "Laravel", color: "pink-text-gradient" },
      { name: "PHP", color: "blue-text-gradient" },
    ],
    image: agcalifornia,
    links: [{ url: "", icon: github, color: "bg-gray-800", altKey: "common.accessWebsite", disabledColor: "dark", disabled: true }],
  },
  {
    id: "a40e6a42-3536-4fde-b801-c3166bd2def1",
    nameKey: "projects.empreenda.name",
    type: "collaborate",
    tags: [
      { name: "Laravel", color: "pink-text-gradient" },
      { name: "PHP", color: "blue-text-gradient" },
    ],
    image: empreenda,
    links: [{ url: "", icon: github, color: "bg-gray-800", altKey: "common.accessWebsite", disabledColor: "dark", disabled: true }],
  },
  {
    id: "3a639afa-0eb2-45c1-9f27-651dfe9f575d",
    nameKey: "projects.uberClone.name",
    type: "personal",
    descriptionKey: "projects.uberClone.description",
    tags: [
      { name: "Expo", color: "pink-text-gradient" },
      { name: "React Native", color: "blue-text-gradient" },
      { name: "Google Maps API", color: "green-text-gradient" },
    ],
    image: uber,
    links: [{ url: "https://github.com/cloviscarmezini/uber-clone", icon: github, color: "bg-gray-800", altKey: "common.accessGithub" }],
  },
  {
    id: "f66b5683-bae1-42db-9811-093dc43cfa96",
    nameKey: "projects.instagramClone.name",
    type: "personal",
    descriptionKey: "projects.instagramClone.description",
    tags: [
      { name: "Expo", color: "pink-text-gradient" },
      { name: "React Native", color: "blue-text-gradient" },
      { name: "Atomic Design", color: "green-text-gradient" },
    ],
    image: instagram,
    links: [{ url: "https://github.com/cloviscarmezini/instagram-clone", icon: github, color: "bg-gray-800", altKey: "common.accessGithub" }],
  },
  {
    id: "f66b5683-bae1-42db-9811-093dc43cfa96",
    nameKey: "projects.tinderClone.name",
    type: "personal",
    descriptionKey: "projects.tinderClone.description",
    tags: [
      { name: "Swift", color: "pink-text-gradient" },
      { name: "Storyboard", color: "green-text-gradient" },
    ],
    image: tinder,
    links: [{ url: "https://github.com/cloviscarmezini/tinder-clone-ios", icon: github, color: "bg-gray-800", altKey: "common.accessGithub" }],
  },
];

export { services, technologies, experiences, testimonials, projects };
